
-- ----------------------------
-- Function structure for ACTIVAR_CUENTA
-- ----------------------------
DROP PROCEDURE IF EXISTS `ACTIVAR_CUENTA`;

DELIMITER //

CREATE
PROCEDURE `ACTIVAR_CUENTA`()
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN
        SET ERR_MSG = SQLCODE;
        OPEN CR_SALIDA FOR
            SELECT '1' AS TIPO, CONCAT('Hubo un error en la activación. Código del error: ', ERR_MSG) AS MENSAJE FROM DUAL;
    ROLLBACK;
    END;
    SELECT PE_USUARIO.USU_ACTIVACION INTO COD FROM PE_USUARIO WHERE PE_USUARIO.ID_USUARIO = USUARIO;
    
    IF COD = CODIGO THEN
    
        SELECT PE_USUARIO.ID_PE_ROL INTO ROL FROM PE_USUARIO WHERE PE_USUARIO.ID_USUARIO = USUARIO;
        
        IF ROL = 1 THEN
            UPDATE PE_USUARIO SET PE_USUARIO.USU_ESTADO = '2',
            PE_USUARIO.USU_ACTIVACION = (SELECT DBMS_RANDOM.string('X', 40) FROM DUAL)
            WHERE PE_USUARIO.ID_USUARIO = USUARIO;
        
            OPEN CR_SALIDA FOR
                SELECT '3' AS TIPO, 'Su cuenta fue activada correctamente. Pero en el momento no podrás ingresar a ella,
                porque no hay convocatorias para proyectos.' AS MENSAJE FROM DUAL;
        ELSE
            UPDATE PE_USUARIO SET PE_USUARIO.USU_ESTADO = '1',
            PE_USUARIO.USU_ACTIVACION = (SELECT DBMS_RANDOM.string('X', 40) FROM DUAL)
            WHERE PE_USUARIO.ID_USUARIO = USUARIO;
        
            OPEN CR_SALIDA FOR
                SELECT '3' AS TIPO, 'Su cuenta fue activada correctamente. Ya puede iniciar sesión.' AS MENSAJE FROM DUAL;
        END IF;
    ELSE
        OPEN CR_SALIDA FOR
            SELECT '2' AS TIPO, 'Su cuenta ya fue activada! Ya puede iniciar sesión.' AS MENSAJE FROM DUAL;
    END IF;
    
    COMMIT;
    
    
END;
//

DELIMITER ;

 ACTIVAR_CUENTA;
/

-- ----------------------------
-- Function structure for CONS_CODIGO_ACTIVACION
-- ----------------------------
DROP PROCEDURE IF EXISTS `CONS_CODIGO_ACTIVACION`;

DELIMITER //

CREATE
PROCEDURE `CONS_CODIGO_ACTIVACION`()
BEGIN
    OPEN CR_SALIDA FOR
        SELECT PE_USUARIO.USU_ACTIVACION AS KEY, PE_USUARIO.ID_USUARIO AS ID
        FROM PE_USUARIO 
        INNER JOIN PE_PERSONA ON(PE_USUARIO.ID_PE_PERSONA = PE_PERSONA.ID_PERSONA)
        WHERE PE_PERSONA.PER_CEDULA = CEDULA;
        
    COMMIT;
END;
//

DELIMITER ;

 CONS_CODIGO_ACTIVACION;
/

-- ----------------------------
-- Function structure for CONS_EVALUACIONES
-- ----------------------------
DROP PROCEDURE IF EXISTS `CONS_EVALUACIONES`;

DELIMITER //

CREATE
PROCEDURE `CONS_EVALUACIONES`()
BEGIN
  OPEN CR_SALIDA FOR
    SELECT PRO.PRO_NOMBRE AS PROYECTO,
    CONCAT(PER.PER_NOMBRES, CONCAT(' ', PER.PER_APELLIDOS)) AS EVALUADOR,
    EVA.ID_EVALUACION AS EVALUACION,
    DATE_FORMAT(EVA.EVA_FECHA, '%Y/%m/%d %H:%i:%s') AS FECHA,
    EVA.EVA_PUNTAJE_TOTAL AS PUNTAJE,
    CASE WHEN EVA.EVA_ESTADO = '0' THEN 'Sin evaluar' ELSE 'Evaluado' END AS ESTADO,
    ARC.ARC_URL AS ARCHIVO
    FROM PE_PROYECTO PRO
    INNER JOIN PE_EVALUACION EVA ON EVA.ID_PE_PROYECTO = PRO.ID_PROYECTO
    INNER JOIN PE_PERSONA PER ON EVA.ID_PE_PERSONA = PER.ID_PERSONA
    INNER JOIN PE_ARCHIVO ARC ON ARC.ID_PE_PROYECTO = PRO.ID_PROYECTO
    WHERE PRO.PRO_ELIMINADO = '0'
    AND ARC.ID_PE_TIPO_DOCUMENTO = 1
    ORDER BY 6 ASC, 2 ASC;
 COMMIT;
END;
//

DELIMITER ;

 CONS_EVALUACIONES;
/

-- ----------------------------
-- Function structure for CONS_EVALUACIONES_REPORT
-- ----------------------------
DROP PROCEDURE IF EXISTS `CONS_EVALUACIONES_REPORT`;

DELIMITER //

CREATE
PROCEDURE `CONS_EVALUACIONES_REPORT`()
BEGIN
    
    OPEN CR_SALIDA FOR
        SELECT ROWNUM AS No,
        PRO.PRO_NOMBRE AS PROYECTO, 
        CONCAT(COO.PER_NOMBRES, CONCAT(' ', COO.PER_APELLIDOS)) AS COORDINADOR,
        CONCAT(CAL.PER_NOMBRES, CONCAT(' ', CAL.PER_APELLIDOS)) AS EVALUADOR,
        (SELECT EI.EVIT_PUNTAJE FROM PE_EVALUACION_ITEM EI WHERE EI.ID_PE_EVALUACION = EVA.ID_EVALUACION AND EI.ID_PE_ITEM = 1) AS PLANTEAMIENTO,
        (SELECT EI.EVIT_PUNTAJE FROM PE_EVALUACION_ITEM EI WHERE EI.ID_PE_EVALUACION = EVA.ID_EVALUACION AND EI.ID_PE_ITEM = 2) AS JUSTIFICACIÓN,
        (SELECT EI.EVIT_PUNTAJE FROM PE_EVALUACION_ITEM EI WHERE EI.ID_PE_EVALUACION = EVA.ID_EVALUACION AND EI.ID_PE_ITEM = 3) AS OBJETIVOS,
        (SELECT EI.EVIT_PUNTAJE FROM PE_EVALUACION_ITEM EI WHERE EI.ID_PE_EVALUACION = EVA.ID_EVALUACION AND EI.ID_PE_ITEM = 4) AS METODOLOGÍA,
        (SELECT EI.EVIT_PUNTAJE FROM PE_EVALUACION_ITEM EI WHERE EI.ID_PE_EVALUACION = EVA.ID_EVALUACION AND EI.ID_PE_ITEM = 5) AS IMPACTO,
        (SELECT EI.EVIT_PUNTAJE FROM PE_EVALUACION_ITEM EI WHERE EI.ID_PE_EVALUACION = EVA.ID_EVALUACION AND EI.ID_PE_ITEM = 7) AS RESULTADOS,
        /*EVA.EVA_OBSERVACIONES AS OBSERVACIONES,*/
        EVA.EVA_PUNTAJE_TOTAL AS PUNTAJE_TOTAL,
        DATE_FORMAT(EVA.EVA_FECHA, '%Y-%m-%d %H:%i:%s') AS FECHA
        FROM PE_PERSONA COO
        INNER JOIN PE_PROYECTO PRO ON PRO.ID_COORDINADOR = COO.ID_PERSONA
        INNER JOIN PE_EVALUACION EVA ON EVA.ID_PE_PROYECTO = PRO.ID_PROYECTO
        INNER JOIN PE_PERSONA CAL ON EVA.ID_PE_PERSONA = CAL.ID_PERSONA
        WHERE EVA.EVA_ESTADO = 1
        AND PRO.PRO_ELIMINADO != '1'
        ORDER BY 1 ASC;
   
    COMMIT; 
END;
//

DELIMITER ;

 CONS_EVALUACIONES_REPORT;
/

-- ----------------------------
-- Function structure for CONS_EVALUACION_ID
-- ----------------------------
DROP PROCEDURE IF EXISTS `CONS_EVALUACION_ID`;

DELIMITER //

CREATE
PROCEDURE `CONS_EVALUACION_ID`()
BEGIN
  OPEN CR_SALIDA FOR
    SELECT PRO.PRO_NOMBRE AS PROYECTO,
    CONCAT(PER.PER_NOMBRES, CONCAT(' ', PER.PER_APELLIDOS)) AS EVALUADOR,
    DATE_FORMAT(EVA.EVA_FECHA, '%Y/%m/%d %H:%i:%s') AS FECHA,
    EVA.EVA_PUNTAJE_TOTAL AS PUNTAJE,
    EVA.EVA_OBSERVACIONES AS OBSERVACIONES,
    ARC.ARC_URL AS ARCHIVO
    FROM PE_PROYECTO PRO
    INNER JOIN PE_EVALUACION EVA ON EVA.ID_PE_PROYECTO = PRO.ID_PROYECTO
    INNER JOIN PE_PERSONA PER ON EVA.ID_PE_PERSONA = PER.ID_PERSONA
    INNER JOIN PE_ARCHIVO ARC ON ARC.ID_PE_PROYECTO = PRO.ID_PROYECTO
    WHERE EVA.ID_EVALUACION = EVALUACION
    AND ARC.ID_PE_TIPO_DOCUMENTO = 1
    ORDER BY 1 ASC;
    
 COMMIT;
END;
//

DELIMITER ;

 CONS_EVALUACION_ID;
/

-- ----------------------------
-- Function structure for CONS_EVALUADORES_PROYECTO
-- ----------------------------
DROP PROCEDURE IF EXISTS `CONS_EVALUADORES_PROYECTO`;

DELIMITER //

CREATE
PROCEDURE `CONS_EVALUADORES_PROYECTO`()
BEGIN
    OPEN CR_SALIDA FOR
        SELECT PE_PERSONA.ID_PERSONA AS ID,
        CONCAT(PE_PERSONA.PER_NOMBRES, CONCAT(' ', CONCAT(PE_PERSONA.PER_APELLIDOS, CONCAT(' - ', PE_PERSONA.PER_CEDULA)))) AS NOMBRE
        FROM PE_PERSONA
        INNER JOIN PE_EVALUACION ON PE_EVALUACION.ID_PE_PERSONA = PE_PERSONA.ID_PERSONA
        INNER JOIN PE_PROYECTO ON PE_EVALUACION.ID_PE_PROYECTO = PE_PROYECTO.ID_PROYECTO
        WHERE PE_PROYECTO.ID_PROYECTO = PROYECTO
        ORDER BY 1 ASC;
    
    COMMIT;
END;
//

DELIMITER ;

 CONS_EVALUADORES_PROYECTO;
/

-- ----------------------------
-- Function structure for CONS_EVALUADOR_CB
-- ----------------------------
DROP PROCEDURE IF EXISTS `CONS_EVALUADOR_CB`;

DELIMITER //

CREATE
PROCEDURE `CONS_EVALUADOR_CB`()
BEGIN
    OPEN CR_SALIDA FOR
        SELECT PE_PERSONA.ID_PERSONA AS ID,
        CONCAT(PE_PERSONA.PER_NOMBRES, CONCAT(' ', CONCAT(PE_PERSONA.PER_APELLIDOS, CONCAT(' - ', PE_PERSONA.PER_CEDULA)))) AS NOMBRE
        FROM PE_PERSONA
        INNER JOIN PE_USUARIO ON PE_USUARIO.ID_PE_PERSONA = PE_PERSONA.ID_PERSONA
        INNER JOIN PE_ROL ON PE_USUARIO.ID_PE_ROL = PE_ROL.ID_ROL
        WHERE PE_ROL.ID_ROL = 2
        AND PE_USUARIO.USU_ESTADO = 1
        ORDER BY 2;
    
    COMMIT;
END;
//

DELIMITER ;

 CONS_EVALUADOR_CB;
/

-- ----------------------------
-- Function structure for CONS_LOGIN
-- ----------------------------
DROP PROCEDURE IF EXISTS `CONS_LOGIN`;

DELIMITER //

CREATE
PROCEDURE `CONS_LOGIN`()
BEGIN    
    SELECT COUNT(PE_USUARIO.ID_USUARIO) INTO CONT 
    FROM PE_USUARIO
    WHERE PE_USUARIO.USU_CORREO = CORREO
    AND PE_USUARIO.USU_CONTRASENA = (SELECT DBMS_OBFUSCATION_TOOLKIT.MD5( INPUT => UTL_RAW.CAST_TO_RAW(CONTRASENA)) FROM DUAL);
    
    IF CONT != 0 THEN
        SELECT PE_USUARIO.USU_ESTADO INTO ESTADO FROM PE_USUARIO WHERE PE_USUARIO.USU_CORREO = CORREO;
    END IF;
    
    IF CONT = 0 THEN
        OPEN CR_SALIDA FOR
            SELECT '1' AS TIPO, '¡Correo o contraseña incorrectos.' AS MENSAJE FROM DUAL;
    ELSEIF ESTADO = 0 THEN
        OPEN CR_SALIDA FOR
            SELECT '1' AS TIPO, 'Su cuenta aún no ha sido activada.' AS MENSAJE FROM DUAL;
    ELSEIF ESTADO = 2 THEN
        OPEN CR_SALIDA FOR
            SELECT '1' AS TIPO, 'Su cuenta está inhabilitada temporalmente.' AS MENSAJE FROM DUAL;
    ELSE
        OPEN CR_SALIDA FOR
            SELECT '3' AS TIPO, '¡Inicio exitoso!' AS MENSAJE FROM DUAL;
    END IF;

    COMMIT;
END;
//

DELIMITER ;

 CONS_LOGIN;
/

-- ----------------------------
-- Function structure for CONS_OBSERVACIONES_EVALUACION
-- ----------------------------
DROP PROCEDURE IF EXISTS `CONS_OBSERVACIONES_EVALUACION`;

DELIMITER //

CREATE
PROCEDURE `CONS_OBSERVACIONES_EVALUACION`()
BEGIN
    SELECT PE_PERSONA.ID_PERSONA INTO ID_PE
    FROM PE_PERSONA
    INNER JOIN PE_USUARIO ON PE_USUARIO.ID_PE_PERSONA = PE_PERSONA.ID_PERSONA
    WHERE USU_CORREO = CORREO;

    OPEN CR_SALIDA FOR
        SELECT PE_EVALUACION.EVA_OBSERVACIONES AS OBSERVACIONES
        FROM PE_EVALUACION
        WHERE PE_EVALUACION.ID_EVALUACION = EVALUACION
        AND PE_EVALUACION.ID_PE_PERSONA = ID_PE;
    
    COMMIT;    
END;
//

DELIMITER ;

 CONS_OBSERVACIONES_EVALUACION;
/

-- ----------------------------
-- Function structure for CONS_PROYECTOS_ALL
-- ----------------------------
DROP PROCEDURE IF EXISTS `CONS_PROYECTOS_ALL`;

DELIMITER //

CREATE
PROCEDURE `CONS_PROYECTOS_ALL`()
BEGIN
    OPEN CR_SALIDA FOR
        SELECT PRO.ID_PROYECTO AS ID,
        PRO.PRO_NOMBRE AS PROYECTO,
        DATE_FORMAT(PRO.PRO_FECHA_PRESENTACION, '%Y-%m-%d') AS PRESENTACION,
        CONCAT(PER.PER_NOMBRES, CONCAT(' ', PER.PER_APELLIDOS)) AS COORDINADOR,
        PER.PER_TELEFONO AS TELEFONO,
        USU.USU_CORREO AS CORREO,
        (SELECT  SARC1.ARC_URL  
        FROM PE_ARCHIVO SARC1
        WHERE SARC1.ID_PE_PROYECTO = PRO.ID_PROYECTO 
        AND SARC1.ID_PE_TIPO_DOCUMENTO = 1) AS ARCHIVO,
        (SELECT  SARC.ARC_URL  
        FROM PE_ARCHIVO  SARC
        WHERE SARC.ID_PE_PROYECTO = PRO.ID_PROYECTO 
        AND SARC.ID_PE_TIPO_DOCUMENTO = 2) AS PRESUPUESTO,
        (SELECT  SARC.ARC_URL  
        FROM PE_ARCHIVO  SARC
        WHERE SARC.ID_PE_PROYECTO = PRO.ID_PROYECTO 
        AND SARC.ID_PE_TIPO_DOCUMENTO = 3) AS INFORME_PARCIAL,
        (SELECT  SARC.ARC_URL  
        FROM PE_ARCHIVO  SARC
        WHERE SARC.ID_PE_PROYECTO = PRO.ID_PROYECTO 
        AND SARC.ID_PE_TIPO_DOCUMENTO = 5) AS INFORME_PARCIAL2,
        (SELECT  SARC.ARC_URL  
        FROM PE_ARCHIVO  SARC
        WHERE SARC.ID_PE_PROYECTO = PRO.ID_PROYECTO 
        AND SARC.ID_PE_TIPO_DOCUMENTO = 4) AS INFORME_FINAL,
        CASE WHEN (SELECT  COUNT(SARC.ARC_URL)  
        FROM PE_ARCHIVO  SARC
        WHERE SARC.ID_PE_PROYECTO = PRO.ID_PROYECTO 
        AND SARC.ID_PE_TIPO_DOCUMENTO = 2) = 0 THEN '' ELSE 'Ver presupuesto' END AS ESTADO_PRESUPUESTO,
        CASE WHEN (SELECT  COUNT(SARC.ARC_URL)  
        FROM PE_ARCHIVO  SARC
        WHERE SARC.ID_PE_PROYECTO = PRO.ID_PROYECTO 
        AND SARC.ID_PE_TIPO_DOCUMENTO = 2) = 0 THEN 'No aprobado' ELSE 'Aprobado' END AS ESTADO,
        CASE WHEN (SELECT  COUNT(SARC.ARC_URL)  
        FROM PE_ARCHIVO  SARC
        WHERE SARC.ID_PE_PROYECTO = PRO.ID_PROYECTO 
        AND SARC.ID_PE_TIPO_DOCUMENTO = 3) = 0 THEN '' ELSE 'Ver informe' END AS ESTADO_INFORME,
        (SELECT COUNT(EVA.ID_EVALUACION) 
        FROM PE_EVALUACION EVA 
        INNER JOIN PE_PROYECTO SPRO ON EVA.ID_PE_PROYECTO = SPRO.ID_PROYECTO
        WHERE SPRO.ID_PROYECTO = PRO.ID_PROYECTO) AS CANT_EVALUADORES
        FROM PE_ARCHIVO ARC
        INNER JOIN PE_PROYECTO PRO ON ARC.ID_PE_PROYECTO = ID_PROYECTO
        INNER JOIN PE_PERSONA PER ON PRO.ID_COORDINADOR = PER.ID_PERSONA
        INNER JOIN PE_USUARIO USU ON USU.ID_PE_PERSONA = PER.ID_PERSONA
        WHERE PRO.PRO_ELIMINADO != '1'
        AND ARC.ID_PE_TIPO_DOCUMENTO = 1
        ORDER BY PRO.ID_PROYECTO;
    
    COMMIT;
END;
//

DELIMITER ;

 CONS_PROYECTOS_ALL;
/

-- ----------------------------
-- Function structure for CONS_PROYECTOS_COORDINADOR
-- ----------------------------
DROP PROCEDURE IF EXISTS `CONS_PROYECTOS_COORDINADOR`;

DELIMITER //

CREATE
PROCEDURE `CONS_PROYECTOS_COORDINADOR`()
BEGIN
    SELECT PE_PERSONA.ID_PERSONA INTO ID_PE
    FROM PE_PERSONA
    INNER JOIN PE_USUARIO ON PE_USUARIO.ID_PE_PERSONA = PE_PERSONA.ID_PERSONA
    WHERE USU_CORREO = CORREO;
    
    OPEN CR_SALIDA FOR
        SELECT PE_PROYECTO.ID_PROYECTO AS PROYECTO_ID,
        PE_PROYECTO.PRO_NOMBRE AS PROYECTO,
        PE_PROYECTO.PRO_METODOLOGIA AS METODOLOGIA,
        PE_PROYECTO.PRO_JUSTIFICACION AS JUSTIFICACION,
        PE_PROYECTO.PRO_PLANTEAMIENTO_PROBLEMA AS PLANTEAMIENTO,
        PE_PROYECTO.PRO_COMPONENTE_INNOVADOR AS IMPACTO,
        PE_PROYECTO.PRO_RESULTADOS_ESPERADOS AS RESULTADOS,
        (SELECT ARC.ARC_URL FROM PE_ARCHIVO ARC WHERE ARC.ID_PE_PROYECTO = PE_PROYECTO.ID_PROYECTO AND ARC.ID_PE_TIPO_DOCUMENTO = '1') AS ARCHIVO,
        (SELECT ARC.ARC_URL FROM PE_ARCHIVO ARC WHERE ARC.ID_PE_PROYECTO = PE_PROYECTO.ID_PROYECTO AND ARC.ID_PE_TIPO_DOCUMENTO = '3') AS PARCIAL,
        (SELECT ARC.ARC_URL FROM PE_ARCHIVO ARC WHERE ARC.ID_PE_PROYECTO = PE_PROYECTO.ID_PROYECTO AND ARC.ID_PE_TIPO_DOCUMENTO = '5') AS PARCIAL2,
        (SELECT ARC.ARC_URL FROM PE_ARCHIVO ARC WHERE ARC.ID_PE_PROYECTO = PE_PROYECTO.ID_PROYECTO AND ARC.ID_PE_TIPO_DOCUMENTO = '4') AS FINAL,
        (SELECT PE_OBJETIVOS.OBJ_DESCRIPCION FROM PE_OBJETIVOS WHERE PE_OBJETIVOS.ID_PE_PROYECTO = PE_PROYECTO.ID_PROYECTO AND OBJ_TIPO = '1') AS GENERAL,
        (SELECT PE_OBJETIVOS.OBJ_DESCRIPCION FROM PE_OBJETIVOS WHERE PE_OBJETIVOS.ID_PE_PROYECTO = PE_PROYECTO.ID_PROYECTO AND OBJ_TIPO = '2') AS ESPECIFICOS
        FROM PE_PROYECTO 
        WHERE PE_PROYECTO.ID_COORDINADOR = ID_PE;
    
    COMMIT;
END;
//

DELIMITER ;

 CONS_PROYECTOS_COORDINADOR;
/

-- ----------------------------
-- Function structure for CONS_PROYECTOS_EVALUADOR
-- ----------------------------
DROP PROCEDURE IF EXISTS `CONS_PROYECTOS_EVALUADOR`;

DELIMITER //

CREATE
PROCEDURE `CONS_PROYECTOS_EVALUADOR`()
BEGIN
    OPEN CR_SALIDA FOR
        SELECT PE_PROYECTO.ID_PROYECTO AS ID,
        PE_PROYECTO.PRO_NOMBRE AS PROYECTO,
        CASE WHEN PE_EVALUACION.EVA_ESTADO = '0' THEN 'Sin evaluar' ELSE 'Evaluado' END AS ESTADO,
        CASE WHEN PE_EVALUACION.EVA_ESTADO = '0' THEN 'Evaluar' ELSE 'Ver evaluación' END AS ENLACE
        FROM PE_PROYECTO
        INNER JOIN PE_EVALUACION ON PE_EVALUACION.ID_PE_PROYECTO = PE_PROYECTO.ID_PROYECTO
        INNER JOIN PE_PERSONA ON PE_EVALUACION.ID_PE_PERSONA = PE_PERSONA.ID_PERSONA
        INNER JOIN PE_USUARIO ON PE_USUARIO.ID_PE_PERSONA = PE_PERSONA.ID_PERSONA
        WHERE PE_USUARIO.USU_CORREO = CORREO
        ORDER BY 1 ASC;
    
    COMMIT;
END;
//

DELIMITER ;

 CONS_PROYECTOS_EVALUADOR;
/

-- ----------------------------
-- Function structure for CONS_PROYECTOS_GRUPOS
-- ----------------------------
DROP PROCEDURE IF EXISTS `CONS_PROYECTOS_GRUPOS`;

DELIMITER //

CREATE
PROCEDURE `CONS_PROYECTOS_GRUPOS`()
BEGIN
    OPEN CR_SALIDA FOR
        SELECT PRO.PRO_NOMBRE AS PROYECTO, 
        CONCAT(COO.PER_NOMBRES, CONCAT(' ', COO.PER_APELLIDOS)) AS COORDINADOR,
        GE.GREX_NOMBRE AS GRUPO_EXTENSION,
        CONCAT(PER.PER_NOMBRES, CONCAT(' ', PER.PER_APELLIDOS)) AS INTEGRANTE, 
        PER.PER_CEDULA AS CEDULA_INTEGRANTE,
        TV.TIVI_NOMBRE AS TIPO_DE_VINCULACION
        FROM PE_PERSONA PER
        INNER JOIN PE_PROYECTO_PERSONA PP ON  PP.ID_PE_PERSONA = PER.ID_PERSONA
        INNER JOIN PE_PROYECTO PRO ON PP.ID_PE_PROYECTO = PRO.ID_PROYECTO
        INNER JOIN PE_TIPO_VINCULACION TV ON PP.ID_PE_TIPO_VINCULACION = TV.ID_TIPO_VINCULACION
        INNER JOIN PE_GRUPO_EXTENSION GE ON GE.ID_GRUPO_EXTENSION = PRO.ID_PE_GRUPO_EXTENSION
        INNER JOIN PE_PERSONA COO ON PRO.ID_COORDINADOR = COO.ID_PERSONA
        ORDER BY 1 ASC;
    COMMIT;
END;
//

DELIMITER ;

 CONS_PROYECTOS_GRUPOS;
/

-- ----------------------------
-- Function structure for CONS_PROYECTO_EVALUACION
-- ----------------------------
DROP PROCEDURE IF EXISTS `CONS_PROYECTO_EVALUACION`;

DELIMITER //

CREATE
PROCEDURE `CONS_PROYECTO_EVALUACION`()
BEGIN
    SELECT PE_PERSONA.ID_PERSONA INTO ID_PE
    FROM PE_PERSONA
    INNER JOIN PE_USUARIO ON PE_USUARIO.ID_PE_PERSONA = PE_PERSONA.ID_PERSONA
    WHERE USU_CORREO = CORREO;
    
    OPEN CR_SALIDA FOR
        SELECT PE_PROYECTO.PRO_NOMBRE AS PROYECTO,
        PE_PROYECTO.PRO_METODOLOGIA AS METODOLOGIA,
        PE_PROYECTO.PRO_JUSTIFICACION AS JUSTIFICACION,
        PE_PROYECTO.PRO_PLANTEAMIENTO_PROBLEMA AS PLANTEAMIENTO,
        PE_PROYECTO.PRO_COMPONENTE_INNOVADOR AS IMPACTO,
        PE_PROYECTO.PRO_RESULTADOS_ESPERADOS AS RESULTADOS,
        (SELECT PE_OBJETIVOS.OBJ_DESCRIPCION FROM PE_OBJETIVOS WHERE PE_OBJETIVOS.ID_PE_PROYECTO = PROYECTO AND OBJ_TIPO = '1') AS GENERAL,
        (SELECT PE_OBJETIVOS.OBJ_DESCRIPCION FROM PE_OBJETIVOS WHERE PE_OBJETIVOS.ID_PE_PROYECTO = PROYECTO AND OBJ_TIPO = '2') AS ESPECIFICOS,
        PE_EVALUACION.ID_EVALUACION AS EVALUACION,
        PE_EVALUACION.EVA_ESTADO AS ESTADO
        FROM PE_PROYECTO 
        INNER JOIN PE_EVALUACION ON PE_EVALUACION.ID_PE_PROYECTO = PE_PROYECTO.ID_PROYECTO
        WHERE PE_PROYECTO.ID_PROYECTO = PROYECTO
        AND PE_EVALUACION.ID_PE_PERSONA = ID_PE
        ORDER BY 1 ASC;
    
    COMMIT;
END;
//

DELIMITER ;

 CONS_PROYECTO_EVALUACION;
/

-- ----------------------------
-- Function structure for CONS_PUNTAJE_ITEMS
-- ----------------------------
DROP PROCEDURE IF EXISTS `CONS_PUNTAJE_ITEMS`;

DELIMITER //

CREATE
PROCEDURE `CONS_PUNTAJE_ITEMS`()
BEGIN

    OPEN CR_SALIDA FOR
        SELECT PE_EVALUACION_ITEM.EVIT_PUNTAJE AS PUNTAJE,
        PE_EVALUACION_ITEM.ID_PE_ITEM AS ITEM_ID,
        PE_EVALUACION_ITEM.EVIT_FECHA_CALIFICACION AS FECHA,
        PE_ITEM.ITE_NOMBRE AS ITEM_NOMBRE
        FROM PE_EVALUACION_ITEM
        INNER JOIN PE_EVALUACION ON PE_EVALUACION_ITEM.ID_PE_EVALUACION = PE_EVALUACION.ID_EVALUACION
        INNER JOIN PE_ITEM ON PE_EVALUACION_ITEM.ID_PE_ITEM = PE_ITEM.ID_ITEM
        WHERE PE_EVALUACION_ITEM.ID_PE_EVALUACION = EVALUACION
        AND PE_EVALUACION_ITEM.ID_PE_ITEM NOT IN(6, 8)
        ORDER BY 2 ASC;
    
    COMMIT;        
END;
//

DELIMITER ;

 CONS_PUNTAJE_ITEMS;
/

-- ----------------------------
-- Function structure for CONS_PUNTAJE_ITEMS_EVALUADOR
-- ----------------------------
DROP PROCEDURE IF EXISTS `CONS_PUNTAJE_ITEMS_EVALUADOR`;

DELIMITER //

CREATE
PROCEDURE `CONS_PUNTAJE_ITEMS_EVALUADOR`()
BEGIN
    SELECT PE_PERSONA.ID_PERSONA INTO ID_PE
    FROM PE_PERSONA
    INNER JOIN PE_USUARIO ON PE_USUARIO.ID_PE_PERSONA = PE_PERSONA.ID_PERSONA
    WHERE USU_CORREO = CORREO;

    OPEN CR_SALIDA FOR
        SELECT PE_EVALUACION_ITEM.EVIT_PUNTAJE AS PUNTAJE,
        PE_EVALUACION_ITEM.ID_PE_ITEM AS ITEM
        FROM PE_EVALUACION_ITEM
        INNER JOIN PE_EVALUACION ON PE_EVALUACION_ITEM.ID_PE_EVALUACION = PE_EVALUACION.ID_EVALUACION
        WHERE PE_EVALUACION_ITEM.ID_PE_EVALUACION = EVALUACION
        AND PE_EVALUACION.ID_PE_PERSONA = ID_PE
        ORDER BY 2 ASC;
    
    COMMIT;        
END;
//

DELIMITER ;

 CONS_PUNTAJE_ITEMS_EVALUADOR;
/

-- ----------------------------
-- Function structure for CONS_ROL_CB
-- ----------------------------
DROP PROCEDURE IF EXISTS `CONS_ROL_CB`;

DELIMITER //

CREATE
PROCEDURE `CONS_ROL_CB`()
BEGIN
    OPEN CR_SALIDA FOR
        SELECT PE_ROL.ID_ROL AS ID,
        PE_ROL.ROL_NOMBRE AS NOMBRE
        FROM PE_ROL
        UNION SELECT 0 AS ID,
        'Todos' AS NOMBRE
        FROM DUAL
        ORDER BY 1 ASC;
    
    COMMIT;
END;
//

DELIMITER ;

 CONS_ROL_CB;
/

-- ----------------------------
-- Function structure for CONS_TIPO_DEPENDENCIA_CB
-- ----------------------------
DROP PROCEDURE IF EXISTS `CONS_TIPO_DEPENDENCIA_CB`;

DELIMITER //

CREATE
PROCEDURE `CONS_TIPO_DEPENDENCIA_CB`()
BEGIN
    OPEN CR_SALIDA FOR
        SELECT PE_TIPO_DEPENDENCIA.ID_TIPO_DEPENDENCIA AS ID, PE_TIPO_DEPENDENCIA.TIDE_NOMBRE AS NOMBRE 
        FROM PE_TIPO_DEPENDENCIA
        ORDER BY 1;
        
    COMMIT;
END;
//

DELIMITER ;

 CONS_TIPO_DEPENDENCIA_CB;
/

-- ----------------------------
-- Function structure for CONS_TIPO_VINCULACION_CB
-- ----------------------------
DROP PROCEDURE IF EXISTS `CONS_TIPO_VINCULACION_CB`;

DELIMITER //

CREATE
PROCEDURE `CONS_TIPO_VINCULACION_CB`()
BEGIN
    OPEN CR_SALIDA FOR
        SELECT PE_TIPO_VINCULACION.ID_TIPO_VINCULACION AS ID, PE_TIPO_VINCULACION.TIVI_NOMBRE AS NOMBRE 
        FROM PE_TIPO_VINCULACION
        ORDER BY 1;
        
    COMMIT;
END;
//

DELIMITER ;

 CONS_TIPO_VINCULACION_CB;
/

-- ----------------------------
-- Function structure for CONS_USUARIOS_ALL
-- ----------------------------
DROP PROCEDURE IF EXISTS `CONS_USUARIOS_ALL`;

DELIMITER //

CREATE
PROCEDURE `CONS_USUARIOS_ALL`()
BEGIN
    OPEN CR_SALIDA FOR
        SELECT CONCAT(PER.PER_NOMBRES, CONCAT(' ', PER.PER_APELLIDOS)) AS NOMBRE,
        PER.PER_CEDULA AS CEDULA,
        PER.PER_TELEFONO AS TELEFONO,
        USU.USU_CORREO AS CORREO,
        PE_ROL.ROL_NOMBRE AS ROL
        FROM PE_PERSONA PER
        INNER JOIN PE_USUARIO USU ON USU.ID_PE_PERSONA = PER.ID_PERSONA
        INNER JOIN PE_ROL ON USU.ID_PE_ROL = PE_ROL.ID_ROL
        ORDER BY ROL DESC, NOMBRE ASC;
    
    COMMIT;
END;
//

DELIMITER ;

 CONS_USUARIOS_ALL;
/

-- ----------------------------
-- Function structure for CONS_USUARIOS_ROL
-- ----------------------------
DROP PROCEDURE IF EXISTS `CONS_USUARIOS_ROL`;

DELIMITER //

CREATE
PROCEDURE `CONS_USUARIOS_ROL`()
BEGIN
    OPEN CR_SALIDA FOR
        SELECT CONCAT(PER.PER_NOMBRES, CONCAT(' ', PER.PER_APELLIDOS)) AS NOMBRE,
        PER.PER_CEDULA AS CEDULA,
        PER.PER_TELEFONO AS TELEFONO,
        USU.USU_CORREO AS CORREO,
        PE_ROL.ROL_NOMBRE AS ROL
        FROM PE_PERSONA PER
        INNER JOIN PE_USUARIO USU ON USU.ID_PE_PERSONA = PER.ID_PERSONA
        INNER JOIN PE_ROL ON USU.ID_PE_ROL = PE_ROL.ID_ROL
        WHERE PE_ROL.ID_ROL = ROL
        ORDER BY ROL DESC, NOMBRE ASC;
        
    COMMIT;
END;
//

DELIMITER ;

 CONS_USUARIOS_ROL;
/

-- ----------------------------
-- Function structure for CONS_USUARIO_CORREO
-- ----------------------------
DROP PROCEDURE IF EXISTS `CONS_USUARIO_CORREO`;

DELIMITER //

CREATE
PROCEDURE `CONS_USUARIO_CORREO`()
BEGIN
    OPEN CR_SALIDA FOR
        SELECT PE_PERSONA.ID_PERSONA AS PERSONA,
        PE_PERSONA.PER_NOMBRES AS NOMBRES,
        PE_PERSONA.PER_APELLIDOS AS APELLIDOS,
        PE_PERSONA.PER_CEDULA AS CEDULA,
        PE_PERSONA.PER_TELEFONO AS TELEFONO,
        PE_USUARIO.USU_CORREO AS CORREO,
        PE_ROL.ROL_NOMBRE AS ROL
        FROM PE_ROL
        INNER JOIN PE_USUARIO ON PE_USUARIO.ID_PE_ROL = PE_ROL.ID_ROL
        INNER JOIN PE_PERSONA ON PE_USUARIO.ID_PE_PERSONA = PE_PERSONA.ID_PERSONA
        WHERE PE_USUARIO.USU_CORREO = CORREO;
   
    COMMIT;     
END;
//

DELIMITER ;

 CONS_USUARIO_CORREO;
/

-- ----------------------------
-- Function structure for CONS_USUARIO_EXISTENCIA
-- ----------------------------
DROP PROCEDURE IF EXISTS `CONS_USUARIO_EXISTENCIA`;

DELIMITER //

CREATE
PROCEDURE `CONS_USUARIO_EXISTENCIA`()
BEGIN
    SELECT COUNT(USU.ID_USUARIO) INTO CANT FROM PE_USUARIO USU WHERE USU_CORREO = CORREO;
   
    IF CANT = 0 THEN
        OPEN CR_SALIDA FOR
            SELECT '1' AS TIPO, 'No se ha encontrado el correo registrado.' AS MENSAJE FROM DUAL;
    ELSE
        OPEN CR_SALIDA FOR
            SELECT USU.ID_USUARIO AS ID, PE.PER_NOMBRES AS NOMBRE, USU.USU_ACTIVACION AS CODIGO, '3' AS TIPO,
            'A su correo se envió la información necesaria para restaurar su contraseña.' AS MENSAJE
            FROM PE_PERSONA PE 
            INNER JOIN PE_USUARIO USU ON USU.ID_PE_PERSONA = PE.ID_PERSONA  
            WHERE USU.USU_CORREO = CORREO;
    END IF;
    
END;
//

DELIMITER ;

 CONS_USUARIO_EXISTENCIA;
/

-- ----------------------------
-- Function structure for INSE_DOCENTE
-- ----------------------------
DROP PROCEDURE IF EXISTS `INSE_DOCENTE`;

DELIMITER //

CREATE
PROCEDURE `INSE_DOCENTE`()
BEGIN
    
    DECLARE EXIT HANDLER FOR SQLSTATE '23000' BEGIN
    ROLLBACK;
        OPEN CR_SALIDA FOR
            SELECT '1' AS TIPO, 'Error! La persona y/o correo ya se encuentran registrados.' AS MENSAJE FROM DUAL;
    END;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN
    ROLLBACK;
        SET ERR_MSG = SQLCODE;
        OPEN CR_SALIDA FOR
            SELECT '1' AS TIPO, CONCAT('No se logró realizar el registro. Código del error: ', ERR_MSG) AS MENSAJE FROM DUAL;
    END;

    SELECT COUNT(PE_PERSONA.ID_PERSONA) INTO ID_PE FROM PE_PERSONA;
    IF ID_PE = 0 THEN
        SET ID_PE = 1;
    ELSE
        SELECT MAX(PE_PERSONA.ID_PERSONA)+1 INTO ID_PE FROM PE_PERSONA;
    END IF;
    INSERT INTO PE_PERSONA (ID_PERSONA, PER_CEDULA, PER_NOMBRES, PER_APELLIDOS, PER_TELEFONO)
    VALUES (ID_PE, CEDULA, UPPER(NOMBRES), UPPER(APELLIDOS), TELEFONO);

    SELECT COUNT(PE_USUARIO.ID_USUARIO) INTO ID_US FROM PE_USUARIO;
    IF ID_US = 0 THEN
        SET ID_US = 1;
    ELSE
        SELECT MAX(PE_USUARIO.ID_USUARIO)+1 INTO ID_US FROM PE_USUARIO;
    END IF;
    INSERT INTO PE_USUARIO (ID_USUARIO, USU_CORREO, USU_CONTRASENA, USU_ACTIVACION, ID_PE_PERSONA, ID_PE_ROL)
    VALUES (ID_US, CORREO,  (SELECT DBMS_OBFUSCATION_TOOLKIT.MD5( INPUT => UTL_RAW.CAST_TO_RAW(CONTRASENA)) FROM DUAL), 
    (SELECT DBMS_RANDOM.string('X', 40) FROM DUAL), ID_PE, 4);
    
    OPEN CR_SALIDA FOR
        SELECT '3' AS TIPO, 'Por favor, verifique su cuenta por medio de un enlace enviado a su correo. 
        Si el correo no llega a la bandeja de entrada, por favor revisa en spam.' AS MENSAJE FROM DUAL;
    COMMIT;
    
            
END;
//

DELIMITER ;

 INSE_DOCENTE;
/

-- ----------------------------
-- Function structure for INSE_EVALUACION
-- ----------------------------
DROP PROCEDURE IF EXISTS `INSE_EVALUACION`;

DELIMITER //

CREATE
PROCEDURE `INSE_EVALUACION`()
BEGIN

    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN
    ROLLBACK;
        SET ERR_MSG = SQLERRM;
        OPEN CR_SALIDA FOR
            SELECT '1' AS TIPO, CONCAT('No se logró realizar el registro. Código del error: ', ERR_MSG) AS MENSAJE FROM DUAL;
    END;

    SELECT COUNT(PE_EVALUACION.ID_EVALUACION) INTO CANT_EVAL
    FROM PE_EVALUACION 
    INNER JOIN PE_PROYECTO ON PE_EVALUACION.ID_PE_PROYECTO = PE_PROYECTO.ID_PROYECTO
    WHERE PE_PROYECTO.ID_PROYECTO = PROYECTO;
    
    IF CANT_EVAL <= 2 THEN
        SELECT COUNT(PE_EVALUACION.ID_EVALUACION) INTO ID_EV FROM PE_EVALUACION;
        IF ID_EV = 0 THEN
            SET ID_EV = 1;
        ELSE
            SELECT MAX(PE_EVALUACION.ID_EVALUACION)+1 INTO ID_EV FROM PE_EVALUACION;
        END IF;
        INSERT INTO PE_EVALUACION (ID_EVALUACION, ID_PE_PROYECTO, ID_PE_PERSONA)
        VALUES (ID_EV, PROYECTO, EVALUADOR);
        
        SELECT COUNT(PE_EVALUACION_ITEM.ID_EVALUACION_ITEM) INTO ID_EI FROM PE_EVALUACION_ITEM;
        IF ID_EI = 0 THEN
            SET ID_EI = 1;
        ELSE
            SELECT MAX(PE_EVALUACION_ITEM.ID_EVALUACION_ITEM)+1 INTO ID_EI FROM PE_EVALUACION_ITEM;
        END IF;
        SELECT COUNT(PE_ITEM.ID_ITEM) INTO CANT FROM PE_ITEM;
        SET I = 1;
        WHILE I <= CANT DO
            INSERT INTO PE_EVALUACION_ITEM (ID_EVALUACION_ITEM, ID_PE_ITEM, ID_PE_EVALUACION)
            VALUES (ID_EI, (SELECT ID_ITEM FROM (SELECT ROWNUM R_, ID_ITEM FROM PE_ITEM) WHERE R_ = I), ID_EV);
            SET ID_EI = ID_EI + 1;
            SET I = I + 1;
        END WHILE;
        
        OPEN CR_SALIDA FOR
            SELECT '3' AS TIPO, 'Evaluador asignado correctamente.' AS MENSAJE FROM DUAL;
    ELSE
        OPEN CR_SALIDA FOR
            SELECT '2' AS TIPO, 'Ya se asignaron los dos evaluadores a este proyecto.' AS MENSAJE FROM DUAL;
    END IF;
    
    COMMIT;
    
            
END;
//

DELIMITER ;

 INSE_EVALUACION;
/

-- ----------------------------
-- Function structure for INSE_EVALUADOR
-- ----------------------------
DROP PROCEDURE IF EXISTS `INSE_EVALUADOR`;

DELIMITER //

CREATE
PROCEDURE `INSE_EVALUADOR`()
BEGIN
    
    DECLARE EXIT HANDLER FOR SQLSTATE '23000' BEGIN
        ROLLBACK;
        OPEN CR_SALIDA FOR
            SELECT '1' AS TIPO, 'Error! La persona y/o correo ya se encuentran registrados.' AS MENSAJE FROM DUAL;
    END;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN
        ROLLBACK;
        SET ERR_MSG = SQLCODE;
        OPEN CR_SALIDA FOR
            SELECT '1' AS TIPO, CONCAT('No se logró realizar el registro. Código del error: ', ERR_MSG) AS MENSAJE FROM DUAL;
    END;

    SELECT COUNT(PE_PERSONA.ID_PERSONA) INTO ID_PE FROM PE_PERSONA;
    IF ID_PE = 0 THEN
        SET ID_PE = 1;
    ELSE
        SELECT MAX(PE_PERSONA.ID_PERSONA)+1 INTO ID_PE FROM PE_PERSONA;
    END IF;
    INSERT INTO PE_PERSONA (ID_PERSONA, PER_CEDULA, PER_NOMBRES, PER_APELLIDOS, PER_TELEFONO)
    VALUES (ID_PE, CEDULA, UPPER(NOMBRES), UPPER(APELLIDOS), TELEFONO);

    SELECT COUNT(PE_USUARIO.ID_USUARIO) INTO ID_US FROM PE_USUARIO;
    IF ID_US = 0 THEN
        SET ID_US = 1;
    ELSE
        SELECT MAX(PE_USUARIO.ID_USUARIO)+1 INTO ID_US FROM PE_USUARIO;
    END IF;
    INSERT INTO PE_USUARIO (ID_USUARIO, USU_CORREO, USU_CONTRASENA, USU_ACTIVACION, ID_PE_PERSONA, ID_PE_ROL)
    VALUES (ID_US, CORREO,  (SELECT DBMS_OBFUSCATION_TOOLKIT.MD5( INPUT => UTL_RAW.CAST_TO_RAW(CONTRASENA)) FROM DUAL), 
    (SELECT DBMS_RANDOM.string('X', 40) FROM DUAL), ID_PE, 2);
    
    OPEN CR_SALIDA FOR
        SELECT '3' AS TIPO, 'Por favor, verifique su cuenta por medio de un enlace enviado a su correo. 
        Si el correo no llega a la bandeja de entrada, por favor revisa en spam.' AS MENSAJE FROM DUAL;
    COMMIT;
    
            
END;
//

DELIMITER ;

 INSE_EVALUADOR;
/

-- ----------------------------
-- Function structure for INSE_INFORME_FINAL
-- ----------------------------
DROP PROCEDURE IF EXISTS `INSE_INFORME_FINAL`;

DELIMITER //

CREATE
PROCEDURE `INSE_INFORME_FINAL`()
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN
    ROLLBACK;
        SET ERR_MSG = SQLERRM;
        OPEN CR_SALIDA FOR
            SELECT '1' AS TIPO, CONCAT('No se logró realizar el registro. Código del error: ', ERR_MSG) AS MENSAJE FROM DUAL;
    END;

    SELECT COUNT(ARC.ID_ARCHIVO) INTO VERS FROM PE_ARCHIVO ARC WHERE ARC.ID_PE_PROYECTO = PROYECTO AND ARC.ID_PE_TIPO_DOCUMENTO = '4';
    
    SET NOM_AR = CONCAT('ARC_INFORME_FINAL_' , IFNULL(PROYECTO, '') , '_v' , IFNULL(VERS, ''));
    SET URL_AR = CONCAT('../Content/Archivos/Proyectos/Informes/' , IFNULL(NOM_AR, '') , IFNULL(TIPO_ARCHIVO, ''));
        
    IF VERS = 0 THEN
    
        SELECT COUNT(PE_ARCHIVO.ID_ARCHIVO) INTO ID_AR FROM PE_ARCHIVO;
        IF ID_AR = 0 THEN
            SET ID_AR = 1;
        ELSE
            SELECT MAX(PE_ARCHIVO.ID_ARCHIVO)+1 INTO ID_AR FROM PE_ARCHIVO;
        END IF;
        INSERT INTO PE_ARCHIVO (ID_ARCHIVO, ARC_NOMBRE, ARC_URL, ARC_TIPO, ID_PE_PROYECTO, ID_PE_TIPO_DOCUMENTO) 
        VALUES (ID_AR, NOM_AR, URL_AR, TIPO_ARCHIVO, PROYECTO, 4);
        
    ELSE
        UPDATE PE_ARCHIVO SET ARC_URL = URL_AR WHERE ID_PE_PROYECTO = PROYECTO AND ID_PE_TIPO_DOCUMENTO = 4;
    END IF;
    
    OPEN CR_SALIDA FOR
        SELECT '3' AS TIPO, 'Archivo registrado correctamente!' AS MENSAJE, URL_AR AS RUTA FROM DUAL;
    
    COMMIT;
    
    
END;
//

DELIMITER ;

 INSE_INFORME_FINAL;
/

-- ----------------------------
-- Function structure for INSE_INFORME_PARCIAL
-- ----------------------------
DROP PROCEDURE IF EXISTS `INSE_INFORME_PARCIAL`;

DELIMITER //

CREATE
PROCEDURE `INSE_INFORME_PARCIAL`()
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN
    ROLLBACK;
        SET ERR_MSG = SQLERRM;
        OPEN CR_SALIDA FOR
            SELECT '1' AS TIPO, CONCAT('No se logró realizar el registro. Código del error: ', ERR_MSG) AS MENSAJE FROM DUAL;
    END;

    SELECT COUNT(ARC.ID_ARCHIVO) INTO VERS FROM PE_ARCHIVO ARC WHERE ARC.ID_PE_PROYECTO = PROYECTO AND ARC.ID_PE_TIPO_DOCUMENTO = '5';
    
    SET NOM_AR = CONCAT('ARC_INFORME_PARCIAL_2_' , IFNULL(PROYECTO, '') , '_v' , IFNULL(VERS, ''));
    SET URL_AR = CONCAT('../Content/Archivos/Proyectos/Informes/' , IFNULL(NOM_AR, '') , IFNULL(TIPO_ARCHIVO, ''));
        
    IF VERS = 0 THEN
    
        SELECT COUNT(PE_ARCHIVO.ID_ARCHIVO) INTO ID_AR FROM PE_ARCHIVO;
        IF ID_AR = 0 THEN
            SET ID_AR = 1;
        ELSE
            SELECT MAX(PE_ARCHIVO.ID_ARCHIVO)+1 INTO ID_AR FROM PE_ARCHIVO;
        END IF;
        INSERT INTO PE_ARCHIVO (ID_ARCHIVO, ARC_NOMBRE, ARC_URL, ARC_TIPO, ID_PE_PROYECTO, ID_PE_TIPO_DOCUMENTO) 
        VALUES (ID_AR, NOM_AR, URL_AR, TIPO_ARCHIVO, PROYECTO, 5);
        
    ELSE
        UPDATE PE_ARCHIVO SET ARC_URL = URL_AR WHERE ID_PE_PROYECTO = PROYECTO AND ID_PE_TIPO_DOCUMENTO = 5;
    END IF;
    
    OPEN CR_SALIDA FOR
        SELECT '3' AS TIPO, 'Archivo registrado correctamente!' AS MENSAJE, URL_AR AS RUTA FROM DUAL;
    
    COMMIT;
    
    
END;
//

DELIMITER ;

 INSE_INFORME_PARCIAL;
/

-- ----------------------------
-- Function structure for INSE_ITEMS_EVALUACION
-- ----------------------------
DROP PROCEDURE IF EXISTS `INSE_ITEMS_EVALUACION`;

DELIMITER //

CREATE
PROCEDURE `INSE_ITEMS_EVALUACION`()
BEGIN

    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN
    ROLLBACK;
        SET ERR_MSG = SQLERRM;
        OPEN CR_SALIDA FOR
            SELECT '1' AS TIPO, CONCAT('No se logró realizar el registro. Código del error: ', ERR_MSG) AS MENSAJE FROM DUAL;
    END;
    SELECT COUNT(PE_EVALUACION_ITEM.ID_EVALUACION_ITEM) INTO ID_EI FROM PE_EVALUACION_ITEM;
    IF ID_EI = 0 THEN
        SET ID_EI = 1;
    ELSE
        SELECT MAX(PE_EVALUACION_ITEM.ID_EVALUACION_ITEM)+1 INTO ID_EI FROM PE_EVALUACION_ITEM;
    END IF;
    SELECT COUNT(PE_ITEM.ID_ITEM) INTO CANT FROM PE_ITEM;
    SET I = 1;
    WHILE I <= CANT DO
        INSERT INTO PE_EVALUACION_ITEM (ID_EVALUACION_ITEM, ID_PE_ITEM, ID_PE_EVALUACION)
        VALUES (ID_EI, (SELECT ID_ITEM FROM (SELECT ROWNUM R_, ID_ITEM FROM PE_ITEM) WHERE R_ = I), EVALUACION);
        SET ID_EI = ID_EI + 1;
        SET I = I + 1;
    END WHILE;
    
    OPEN CR_SALIDA FOR
        SELECT '3' AS TIPO, 'Items asignados correctamente.' AS MENSAJE FROM DUAL;
    COMMIT;
    
            
END;
//

DELIMITER ;

 INSE_ITEMS_EVALUACION;
/

-- ----------------------------
-- Function structure for INSE_PRESUPUESTO
-- ----------------------------
DROP PROCEDURE IF EXISTS `INSE_PRESUPUESTO`;

DELIMITER //

CREATE
PROCEDURE `INSE_PRESUPUESTO`()
BEGIN

    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN
    ROLLBACK;
        SET ERR_MSG = SQLCODE;
        OPEN CR_SALIDA FOR
            SELECT '1' AS TIPO, CONCAT('No se logró realizar el registro. Código del error: ', ERR_MSG) AS MENSAJE FROM DUAL;
    END;
    
    SELECT COUNT(PE_ARCHIVO.ID_ARCHIVO) INTO ID_AR FROM PE_ARCHIVO;
    IF ID_AR = 0 THEN
        SET ID_AR = 1;
    ELSE
        SELECT MAX(PE_ARCHIVO.ID_ARCHIVO)+1 INTO ID_AR FROM PE_ARCHIVO;
    END IF;
    SET NOM_AR = CONCAT('ARC_PRESUPUESTO_PROYECTO_', PROYECTO);
    SET URL_AR = CONCAT('../Content/Archivos/Proyectos/Presupuesto/', CONCAT(NOM_AR, TIPO_ARCHIVO));
    INSERT INTO PE_ARCHIVO (ID_ARCHIVO, ARC_NOMBRE, ARC_URL, ARC_TIPO, ID_PE_PROYECTO, ID_PE_TIPO_DOCUMENTO) 
    VALUES (ID_AR, NOM_AR, URL_AR, TIPO_ARCHIVO, PROYECTO, 2);
        
    OPEN CR_SALIDA FOR
        SELECT '3' AS TIPO, 'Presupuesto guardado correctamente.' AS MENSAJE, URL_AR AS RUTA FROM DUAL;
    COMMIT;
    
            
END;
//

DELIMITER ;

 INSE_PRESUPUESTO;
/

-- ----------------------------
-- Function structure for INSE_PROYECTO
-- ----------------------------
DROP PROCEDURE IF EXISTS `INSE_PROYECTO`;

DELIMITER //

CREATE
PROCEDURE `INSE_PROYECTO`()
BEGIN
    DECLARE EXIT HANDLER FOR SQLSTATE '23000' BEGIN
    ROLLBACK;
        OPEN CR_SALIDA FOR
            SELECT '1' AS TIPO, 'Ya tienes registrado un proyecto con el mismo nombre.' AS MENSAJE FROM DUAL;
    END;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN
    ROLLBACK;
        SET ERR_MSG = SQLERRM;
        OPEN CR_SALIDA FOR
            SELECT '1' AS TIPO, CONCAT('No se logró realizar el registro. Código del error: ', ERR_MSG) AS MENSAJE FROM DUAL;
    END;

    SELECT COUNT(PE_GRUPO_EXTENSION.ID_GRUPO_EXTENSION) INTO ID_GE FROM PE_GRUPO_EXTENSION;
    IF ID_GE = 0 THEN
        SET ID_GE = 1;
    ELSE
        SELECT MAX(PE_GRUPO_EXTENSION.ID_GRUPO_EXTENSION)+1 INTO ID_GE FROM PE_GRUPO_EXTENSION;
    END IF;
    INSERT INTO PE_GRUPO_EXTENSION (ID_GRUPO_EXTENSION, GREX_NOMBRE) 
    VALUES (ID_GE, GRUPO_EXTENSION);

    SELECT PE_PERSONA.ID_PERSONA INTO ID_CO FROM PE_USUARIO
    INNER JOIN PE_PERSONA ON PE_USUARIO.ID_PE_PERSONA = PE_PERSONA.ID_PERSONA
    WHERE PE_USUARIO.USU_CORREO = COORDINADOR;

    SELECT COUNT(PE_PROYECTO.ID_PROYECTO) INTO ID_PR FROM PE_PROYECTO;
    IF ID_PR = 0 THEN
        SET ID_PR = 1;
    ELSE
        SELECT MAX(PE_PROYECTO.ID_PROYECTO)+1 INTO ID_PR FROM PE_PROYECTO;
    END IF;
    INSERT INTO PE_PROYECTO (ID_PROYECTO, PRO_NOMBRE, PRO_FECHA_INICIO, PRO_FECHA_FIN, PRO_PLANTEAMIENTO_PROBLEMA, 
    PRO_JUSTIFICACION, PRO_METODOLOGIA, PRO_COMPONENTE_INNOVADOR, PRO_RESULTADOS_ESPERADOS,
    ID_COORDINADOR, ID_PE_GRUPO_EXTENSION, ID_PE_POBLACION, ID_PE_DEPENDENCIA_PROYECTO)
    VALUES (ID_PR, UPPER(NOMBRE), STR_TO_DATE(FECHA_INICIO, '%Y/%m/%d'), STR_TO_DATE(FECHA_FIN, '%Y/%m/%d'), PLANTEAMIENTO, JUSTIFICACION, 
    METODOLOGIA, COMPONENTE_INNOVADOR, RESULTADOS_ESPERADOS, ID_CO, ID_GE, POBLACION, DEPENDENCIA);

    /*SELECT COUNT(PE_PROYECTO_PERSONA.ID_PROYECTO_PERSONA) INTO ID_PP FROM PE_PROYECTO_PERSONA;
    IF ID_PP = 0 THEN
        ID_PP := 1;
    ELSE
        SELECT MAX(PE_PROYECTO_PERSONA.ID_PROYECTO_PERSONA)+1 INTO ID_PP FROM PE_PROYECTO_PERSONA;
    END IF;
    INSERT INTO PE_PROYECTO_PERSONA (ID_PROYECTO_PERSONA, ID_PE_PROYECTO, ID_PE_PERSONA, ID_PE_TIPO_VINCULACION) 
    VALUES (ID_PP, ID_PR, null, 5);
    INSERT INTO PE_PROYECTO_PERSONA (ID_PROYECTO_PERSONA, ID_PE_PROYECTO, ID_PE_PERSONA, ID_PE_TIPO_VINCULACION) 
    VALUES ((ID_PP+1), ID_PR, null, 5);*/
    
    SELECT COUNT(PE_OBJETIVOS.ID_OBJETIVO) INTO ID_OB FROM PE_OBJETIVOS;
    IF ID_OB = 0 THEN
        SET ID_OB = 1;
    ELSE
        SELECT MAX(PE_OBJETIVOS.ID_OBJETIVO)+1 INTO ID_OB FROM PE_OBJETIVOS;
    END IF;
    INSERT INTO PE_OBJETIVOS (ID_OBJETIVO, OBJ_DESCRIPCION, OBJ_TIPO, ID_PE_PROYECTO) 
    VALUES (ID_OB, OBJETIVO_GENERAL, 1, ID_PR);
    INSERT INTO PE_OBJETIVOS (ID_OBJETIVO, OBJ_DESCRIPCION, OBJ_TIPO, ID_PE_PROYECTO)  
    VALUES ((ID_OB+1), OBJETIVOS_ESPECIFICOS, 2, ID_PR);
    
    SELECT COUNT(PE_ARCHIVO.ID_ARCHIVO) INTO ID_AR FROM PE_ARCHIVO;
    IF ID_AR = 0 THEN
        SET ID_AR = 1;
    ELSE
        SELECT MAX(PE_ARCHIVO.ID_ARCHIVO)+1 INTO ID_AR FROM PE_ARCHIVO;
    END IF;
    SET NOM_AR = CONCAT('ARC_PROYECTO_', ID_PR);
    SET URL_AR = CONCAT('../Content/Archivos/Proyectos/', CONCAT(NOM_AR, TIPO_ARCHIVO));
    INSERT INTO PE_ARCHIVO (ID_ARCHIVO, ARC_NOMBRE, ARC_URL, ARC_TIPO, ID_PE_PROYECTO, ID_PE_TIPO_DOCUMENTO) 
    VALUES (ID_AR, NOM_AR, URL_AR, TIPO_ARCHIVO, ID_PR, 1);
        
    OPEN CR_SALIDA FOR
        SELECT '3' AS TIPO, 'Proyecto registrado correctamente!' AS MENSAJE, URL_AR AS RUTA FROM DUAL;
    
    COMMIT;
    
    
END;
//

DELIMITER ;

 INSE_PROYECTO;
/

-- ----------------------------
-- Function structure for RECUPERAR_CONTRASENA
-- ----------------------------
DROP PROCEDURE IF EXISTS `RECUPERAR_CONTRASENA`;

DELIMITER //

CREATE
PROCEDURE `RECUPERAR_CONTRASENA`()
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN
        SET ERR_MSG = SQLCODE;
        OPEN CR_SALIDA FOR
            SELECT '1' AS TIPO, CONCAT('Hubo un error en el registro. Código del error: ', ERR_MSG) AS MENSAJE FROM DUAL;
    ROLLBACK;
    END;
    SELECT USU.USU_ACTIVACION INTO COD FROM PE_USUARIO USU WHERE USU.ID_USUARIO = USUARIO;
    
    IF COD = CODIGO THEN
        
        UPDATE PE_USUARIO 
        SET USU_CONTRASENA = (SELECT DBMS_OBFUSCATION_TOOLKIT.MD5( INPUT => UTL_RAW.CAST_TO_RAW(CONTRASENA)) FROM DUAL)
        WHERE ID_USUARIO = USUARIO;
        
        OPEN CR_SALIDA FOR
            SELECT '3' AS TIPO, 
            CONCAT(IFNULL((SELECT PE.PER_NOMBRES FROM PE_PERSONA PE 
            INNER JOIN PE_USUARIO USU ON PE.ID_PERSONA = USU.ID_PE_PERSONA WHERE USU.ID_USUARIO = USUARIO), '') 
            ,', tu contraseña fue actualizada correctamente.') AS MENSAJE FROM DUAL;
    ELSE
        OPEN CR_SALIDA FOR
            SELECT '1' AS TIPO, 'No se pudo identificar ninguna cuenta.' AS MENSAJE FROM DUAL;
    END IF;
    
    COMMIT;
    
    
END;
//

DELIMITER ;

 RECUPERAR_CONTRASENA;
/

-- ----------------------------
-- Function structure for UPDA_ARCHVO_PROYECTO
-- ----------------------------
DROP PROCEDURE IF EXISTS `UPDA_ARCHVO_PROYECTO`;

DELIMITER //

CREATE
PROCEDURE `UPDA_ARCHVO_PROYECTO`()
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN
    ROLLBACK;
        SET ERR_MSG = SQLerrm;
        OPEN CR_SALIDA FOR
            SELECT '1' AS TIPO, CONCAT('No se logró realizar el registro. Código del error: ', ERR_MSG) AS MENSAJE FROM DUAL;
    END;

    SET NOM_AR = CONCAT('ARC2_PROYECTO_', PROYECTO);
    SET URL_AR = CONCAT('../Content/Archivos/Proyectos/', CONCAT(NOM_AR, TIPO_ARCHIVO));
    
    UPDATE PE_ARCHIVO
    SET ARC_URL = URL_AR,
    ARC_NOMBRE = NOM_AR,
    ARC_TIPO = TIPO_ARCHIVO
    WHERE ID_PE_PROYECTO = PROYECTO;
    
    OPEN CR_SALIDA FOR
        SELECT '3' AS TIPO, 'Archivo actualizado correctamente!' AS MENSAJE, URL_AR AS RUTA FROM DUAL;
    
    COMMIT;
    
    
END;
//

DELIMITER ;

 UPDA_ARCHVO_PROYECTO;
/

-- ----------------------------
-- Function structure for UPDA_CONTRASENA
-- ----------------------------
DROP PROCEDURE IF EXISTS `UPDA_CONTRASENA`;

DELIMITER //

CREATE
PROCEDURE `UPDA_CONTRASENA`()
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN
        ROLLBACK;
        SET ERR_MSG = SQLCODE;
        OPEN CR_SALIDA FOR
            SELECT '1' AS TIPO, CONCAT('No se logró realizar el registro. Código del error: ', ERR_MSG) AS MENSAJE FROM DUAL;
    END;
    SELECT PE_USUARIO.USU_CONTRASENA INTO CA
    FROM PE_USUARIO
    WHERE PE_USUARIO.USU_CORREO = CORREO;
    
    SELECT DBMS_OBFUSCATION_TOOLKIT.MD5( INPUT => UTL_RAW.CAST_TO_RAW(CONTRASENA_ACTUAL)) INTO CA_IN FROM DUAL;
    
    IF CA = CA_IN THEN
        UPDATE PE_USUARIO
        SET USU_CONTRASENA = (SELECT DBMS_OBFUSCATION_TOOLKIT.MD5( INPUT => UTL_RAW.CAST_TO_RAW(CONTRASENA_NUEVA)) FROM DUAL)
        WHERE PE_USUARIO.USU_CORREO = CORREO;
        
        OPEN CR_SALIDA FOR
            SELECT '3' AS TIPO, 'Contraseña actualizada correctamente.' AS MENSAJE FROM DUAL;
    ELSE
        OPEN CR_SALIDA FOR
            SELECT '1' AS TIPO, 'Contraseña actual incorrecta.' AS MENSAJE FROM DUAL;
    END IF;
    
    COMMIT;


END;
//

DELIMITER ;

 UPDA_CONTRASENA;
/

-- ----------------------------
-- Function structure for UPDA_EVALUACION
-- ----------------------------
DROP PROCEDURE IF EXISTS `UPDA_EVALUACION`;

DELIMITER //

CREATE
PROCEDURE `UPDA_EVALUACION`()
BEGIN
    
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN
    ROLLBACK;
        SET ERR_MSG = SQLCODE;
        OPEN CR_SALIDA FOR
            SELECT '1' AS TIPO, CONCAT('No se logró realizar el registro. Código del error: ', ERR_MSG) AS MENSAJE FROM DUAL;
    END;
  
    SELECT PE_EVALUACION.EVA_ESTADO INTO ESTADO_EVA
    FROM PE_EVALUACION
    WHERE PE_EVALUACION.ID_EVALUACION = EVALUACION;
    
    IF ESTADO_EVA = 0 THEN
    
        UPDATE PE_EVALUACION_ITEM
        SET EVIT_PUNTAJE = PLANTEAMIENTO
        WHERE ID_PE_ITEM = 1 
        AND ID_PE_EVALUACION = EVALUACION;
    
        UPDATE PE_EVALUACION_ITEM
        SET EVIT_PUNTAJE = JUSTIFICACION
        WHERE ID_PE_ITEM = 2 
        AND ID_PE_EVALUACION = EVALUACION;
    
        UPDATE PE_EVALUACION_ITEM
        SET EVIT_PUNTAJE = OBJETIVOS
        WHERE ID_PE_ITEM = 3 
        AND ID_PE_EVALUACION = EVALUACION;
    
        UPDATE PE_EVALUACION_ITEM
        SET EVIT_PUNTAJE = METODOLOGIA
        WHERE ID_PE_ITEM = 4 
        AND ID_PE_EVALUACION = EVALUACION;
    
        UPDATE PE_EVALUACION_ITEM
        SET EVIT_PUNTAJE = IMPACTO
        WHERE ID_PE_ITEM = 5 
        AND ID_PE_EVALUACION = EVALUACION;
    
        UPDATE PE_EVALUACION_ITEM
        SET EVIT_PUNTAJE = RESULTADOS
        WHERE ID_PE_ITEM = 7 
        AND ID_PE_EVALUACION = EVALUACION;
    
        UPDATE PE_EVALUACION
        SET EVA_OBSERVACIONES = OBSERVACIONES,
        EVA_FECHA = SYSDATE(),
        EVA_ESTADO = '1',
        EVA_PUNTAJE_TOTAL = (SELECT SUM(PE_EVALUACION_ITEM.EVIT_PUNTAJE) FROM PE_EVALUACION_ITEM
            WHERE PE_EVALUACION_ITEM.ID_PE_EVALUACION = EVALUACION)
        WHERE ID_EVALUACION = EVALUACION;
  
        OPEN CR_SALIDA FOR
            SELECT '3' AS TIPO, 'Evaluación guardada correctamente. A partir de ahora no podrás modificarla.' AS MENSAJE FROM DUAL;
    ELSE
        OPEN CR_SALIDA FOR
            SELECT '1' AS TIPO, 'La evaluación fue registrada anteriormente..' AS MENSAJE FROM DUAL;
    END IF;
    
    COMMIT;
    
            
    
END;
//

DELIMITER ;

 UPDA_EVALUACION;
/

-- ----------------------------
-- Function structure for UPDA_ITEM_EVALUACION
-- ----------------------------
DROP PROCEDURE IF EXISTS `UPDA_ITEM_EVALUACION`;

DELIMITER //

CREATE
PROCEDURE `UPDA_ITEM_EVALUACION`()
BEGIN
    
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN
    ROLLBACK;
        SET ERR_MSG = SQLCODE;
        OPEN CR_SALIDA FOR
            SELECT '1' AS TIPO, CONCAT('No se logró realizar el registro. Código del error: ', ERR_MSG) AS MENSAJE FROM DUAL;
    END;
  
    SELECT PE_EVALUACION.EVA_ESTADO INTO ESTADO_EVA
    FROM PE_EVALUACION
    WHERE PE_EVALUACION.ID_EVALUACION = EVALUACION;
  
    IF ESTADO_EVA = 0 THEN
        UPDATE PE_EVALUACION_ITEM
        SET EVIT_PUNTAJE = PUNTAJE,
        EVIT_FECHA_CALIFICACION = SYSDATE()
        WHERE ID_PE_ITEM = ITEM 
        AND ID_PE_EVALUACION = EVALUACION;
        OPEN CR_SALIDA FOR
            SELECT '3' AS TIPO, 'Puntuación guardada correctamente' AS MENSAJE FROM DUAL;
    ELSE
        OPEN CR_SALIDA FOR
            SELECT '1' AS TIPO, 'Ya finalizaste la evaluación. Ahora no puedes modificar los puntajes.' AS MENSAJE FROM DUAL;
    END IF;
  
    COMMIT;
    
            
END;
//

DELIMITER ;

 UPDA_ITEM_EVALUACION;
/

-- ----------------------------
-- Function structure for UPDA_PERSONA
-- ----------------------------
DROP PROCEDURE IF EXISTS `UPDA_PERSONA`;

DELIMITER //

CREATE
PROCEDURE `UPDA_PERSONA`()
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN
        ROLLBACK;
        SET ERR_MSG = SQLCODE;
        OPEN CR_SALIDA FOR
            SELECT '1' AS TIPO, CONCAT('No se logró realizar la actualización. Código del error: ', ERR_MSG) AS MENSAJE FROM DUAL;
    END;

    SELECT PE_USUARIO.ID_PE_PERSONA INTO ID_PE
    FROM PE_USUARIO
    WHERE PE_USUARIO.USU_CORREO = CORREO;

    UPDATE PE_PERSONA
    SET PER_NOMBRES = UPPER(NOMBRES),
    PER_APELLIDOS = UPPER(APELLIDOS),
    PER_TELEFONO = TELEFONO
    WHERE ID_PERSONA = ID_PE;
    
    OPEN CR_SALIDA FOR
            SELECT '3' AS TIPO, 'Datos actualizados correctamente.' AS MENSAJE FROM DUAL;
            
    COMMIT;

            
END;
//

DELIMITER ;

 UPDA_PERSONA;
/